application: whatshouldilistennext
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: GAEproject.wsgi.application

libraries:
- name: django
  version: 1.5
